//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/game_deploy_person.proto
namespace game_deploy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PERSON")]
  public partial class PERSON : global::ProtoBuf.IExtensible
  {
    public PERSON() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private uint _age = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint age
    {
      get { return _age; }
      set { _age = value; }
    }
    private readonly global::System.Collections.Generic.List<game_deploy.PERSON.grade> _grade_arr = new global::System.Collections.Generic.List<game_deploy.PERSON.grade>();
    [global::ProtoBuf.ProtoMember(4, Name=@"grade_arr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<game_deploy.PERSON.grade> grade_arr
    {
      get { return _grade_arr; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"grade")]
  public partial class grade : global::ProtoBuf.IExtensible
  {
    public grade() {}
    
    private string _gradename = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gradename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gradename
    {
      get { return _gradename; }
      set { _gradename = value; }
    }
    private uint _start_year = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"start_year", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint start_year
    {
      get { return _start_year; }
      set { _start_year = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PERSON_ARRAY")]
  public partial class PERSON_ARRAY : global::ProtoBuf.IExtensible
  {
    public PERSON_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<game_deploy.PERSON> _items = new global::System.Collections.Generic.List<game_deploy.PERSON>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<game_deploy.PERSON> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}